"""create reservations table

Revision ID: 2c469157ee84
Revises: afaa88d65575
Create Date: 2025-12-15 06:28:29.832015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c469157ee84'
down_revision = 'afaa88d65575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('instagram', sa.String(length=120), nullable=True),
    sa.Column('reservation_code', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('created', 'cancelled', 'checked_in', name='reservation_status_enum'), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('scanned_by_user_id', sa.Integer(), nullable=True),
    sa.Column('scan_count', sa.Integer(), nullable=False),
    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('email_send_status', sa.String(length=30), nullable=True),
    sa.Column('email_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scanned_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservations_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_reservation_code'), ['reservation_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservations_reservation_code'))
        batch_op.drop_index(batch_op.f('ix_reservations_event_id'))
        batch_op.drop_index(batch_op.f('ix_reservations_email'))

    op.drop_table('reservations')
    # ### end Alembic commands ###
