"""add event_access_codes

Revision ID: 477f30f3fef4
Revises: 2c469157ee84
Create Date: 2025-12-15 18:59:50.110319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477f30f3fef4'
down_revision = '2c469157ee84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_access_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('access_code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('scan_count', sa.Integer(), nullable=False),
    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_access_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_access_codes_access_code'), ['access_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_event_access_codes_event_id'), ['event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_access_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_access_codes_event_id'))
        batch_op.drop_index(batch_op.f('ix_event_access_codes_access_code'))

    op.drop_table('event_access_codes')
    # ### end Alembic commands ###
